using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Primitives;
using Avalonia.Controls.Presenters;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Media;
using Avalonia.Threading;
using Avalonia.VisualTree;
using KnobForge.App.Controls;
using KnobForge.Core;
using KnobForge.Core.Scene;
using KnobForge.Rendering;
using SkiaSharp;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Numerics;
using System.Reflection;

namespace KnobForge.App.Views
{
        public partial class MainWindow : Window
        {
            private readonly KnobProject _project;
            private readonly MetalViewport? _metalViewport;
            private readonly Control? _viewportOverlay;
            private readonly Border? _paintHudBorder;
            private readonly TextBlock? _paintHudTitleText;
            private readonly TextBlock? _paintHudLine1Text;
            private readonly TextBlock? _paintHudLine2Text;
            private readonly TextBlock? _paintHudLine3Text;
            private readonly TextBlock? _paintHudLine4Text;
            private readonly ListBox? _sceneListBox;
            private readonly TabControl? _inspectorTabControl;
            private readonly TabItem? _lightingTabItem;
            private readonly TabItem? _modelTabItem;
            private readonly TextBlock? _nodeInspectorContextText;
            private readonly Expander? _nodeReferenceProfilesExpander;
            private readonly Expander? _nodeTransformExpander;
            private readonly Expander? _nodeBodyShapeExpander;
            private readonly Expander? _nodeSliderAssemblyExpander;
            private readonly Expander? _nodeToggleAssemblyExpander;
            private readonly Expander? _nodePushButtonAssemblyExpander;
            private readonly Expander? _nodeSpiralRidgeExpander;
            private readonly Expander? _nodeGripExpander;
            private readonly Expander? _nodeCollarExpander;
            private readonly Expander? _nodeRotaryIndicatorExpander;
            private readonly Expander? _nodeIndicatorLightAssemblyExpander;
            private readonly Expander? _nodeMaterialExpander;
            private readonly Expander? _nodeSurfaceTextureExpander;
            private readonly Expander? _nodeMicroDetailExpander;
            private readonly TabItem? _brushTabItem;
            private readonly TabItem? _sceneTabItem;
            private readonly TabItem? _shadowsTabItem;
            private readonly TabItem? _materialGraphTabItem;
            private readonly CheckBox? _graphEnabledCheckBox;
            private readonly TextBlock? _graphValidationText;
            private readonly ListBox? _graphNodeListBox;
            private readonly ComboBox? _addNodeTypeCombo;
            private readonly Button? _addNodeButton;
            private readonly Button? _removeNodeButton;
            private readonly Expander? _nodePropertiesExpander;
            private readonly StackPanel? _nodePropertiesPanel;
            private readonly ListBox? _graphConnectionListBox;
            private readonly Button? _addConnectionButton;
            private readonly Button? _removeConnectionButton;
            private readonly Button? _graphPreviewBakeButton;
            private readonly Image? _graphPreviewImage;
            private readonly Button? _undoButton;
            private readonly Button? _redoButton;
            private readonly ScrollViewer? _inspectorScrollViewer;
            private readonly TextBox? _inspectorSearchTextBox;
            private readonly TextBlock? _runtimeDiagnosticsText;
            private readonly ListBox? _inspectorSearchResultsListBox;
            private readonly ListBox? _recentTweaksListBox;
            private readonly Button? _favoriteReferenceProfilesButton;
            private readonly Button? _favoriteRoughnessButton;
            private readonly Button? _favoriteScratchDepthButton;
            private readonly Button? _favoriteCollarPresetButton;
            private readonly Button? _favoriteShadowSoftnessButton;
            private readonly Button? _favoriteEnvIntensityButton;
            private readonly ComboBox? _lightingModeCombo;
            private readonly ListBox? _lightListBox;
        private readonly Button? _addLightButton;
        private readonly Button? _removeLightButton;
        private readonly Button? _resetViewButton;
        private readonly ValueInput? _rotationInput;
        private readonly ComboBox? _lightTypeCombo;
        private readonly ValueInput? _lightXInput;
        private readonly ValueInput? _lightYInput;
        private readonly ValueInput? _lightZInput;
        private readonly ValueInput? _directionInput;
        private readonly ValueInput? _intensityInput;
        private readonly ValueInput? _falloffInput;
        private readonly ValueInput? _lightRInput;
        private readonly ValueInput? _lightGInput;
        private readonly ValueInput? _lightBInput;
        private readonly ValueInput? _diffuseBoostInput;
        private readonly ValueInput? _specularBoostInput;
        private readonly ValueInput? _specularPowerInput;
        private readonly ValueInput? _modelRadiusInput;
        private readonly ValueInput? _modelHeightInput;
        private readonly ValueInput? _modelTopScaleInput;
        private readonly ValueInput? _modelBevelInput;
        private readonly ComboBox? _referenceStyleCombo;
        private readonly TextBox? _referenceStyleSaveNameTextBox;
        private readonly Button? _saveReferenceProfileButton;
        private readonly Button? _overwriteReferenceProfileButton;
        private readonly Button? _renameReferenceProfileButton;
        private readonly Button? _duplicateReferenceProfileButton;
        private readonly Button? _deleteReferenceProfileButton;
        private readonly TextBlock? _referenceProfileStatusText;
        private readonly ComboBox? _bodyStyleCombo;
        private readonly ValueInput? _bevelCurveInput;
        private readonly ValueInput? _crownProfileInput;
        private readonly ValueInput? _bodyTaperInput;
        private readonly ValueInput? _bodyBulgeInput;
        private readonly ValueInput? _modelSegmentsInput;
        private readonly ComboBox? _sliderAssemblyModeCombo;
        private readonly Button? _refreshSliderLibraryButton;
        private readonly ComboBox? _sliderBackplateMeshCombo;
        private readonly ComboBox? _sliderThumbMeshCombo;
        private readonly ComboBox? _sliderThumbProfileCombo;
        private readonly ComboBox? _sliderTrackStyleCombo;
        private readonly ValueInput? _sliderBackplateWidthInput;
        private readonly ValueInput? _sliderBackplateHeightInput;
        private readonly ValueInput? _sliderBackplateThicknessInput;
        private readonly ValueInput? _sliderThumbWidthInput;
        private readonly ValueInput? _sliderThumbHeightInput;
        private readonly ValueInput? _sliderThumbDepthInput;
        private readonly ValueInput? _sliderTrackWidthInput;
        private readonly ValueInput? _sliderTrackDepthInput;
        private readonly ValueInput? _sliderRailHeightInput;
        private readonly ValueInput? _sliderRailSpacingInput;
        private readonly ValueInput? _sliderThumbRidgeCountInput;
        private readonly ValueInput? _sliderThumbRidgeDepthInput;
        private readonly ValueInput? _sliderThumbCornerRadiusInput;
        private readonly Button? _refreshPushButtonLibraryButton;
        private readonly ComboBox? _pushButtonBaseMeshCombo;
        private readonly ComboBox? _pushButtonCapMeshCombo;
        private readonly ComboBox? _pushButtonCapProfileCombo;
        private readonly ComboBox? _pushButtonBezelProfileCombo;
        private readonly ComboBox? _pushButtonSkirtStyleCombo;
        private readonly ValueInput? _pushButtonPressAmountInput;
        private readonly ValueInput? _pushButtonBezelChamferSizeInput;
        private readonly ValueInput? _pushButtonCapOverhangInput;
        private readonly ValueInput? _pushButtonCapSegmentsInput;
        private readonly ValueInput? _pushButtonBezelSegmentsInput;
        private readonly ValueInput? _pushButtonSkirtHeightInput;
        private readonly ValueInput? _pushButtonSkirtRadiusInput;
        private readonly ComboBox? _toggleAssemblyModeCombo;
        private readonly Button? _refreshToggleLibraryButton;
        private readonly ComboBox? _toggleBaseMeshCombo;
        private readonly ComboBox? _toggleLeverMeshCombo;
        private readonly ComboBox? _toggleStateCountCombo;
        private readonly ValueInput? _toggleStateIndexInput;
        private readonly ValueInput? _toggleMaxAngleInput;
        private readonly ValueInput? _togglePlateWidthInput;
        private readonly ValueInput? _togglePlateHeightInput;
        private readonly ValueInput? _togglePlateThicknessInput;
        private readonly ValueInput? _togglePlateOffsetYInput;
        private readonly ValueInput? _togglePlateOffsetZInput;
        private readonly ValueInput? _toggleBushingRadiusInput;
        private readonly ValueInput? _toggleBushingHeightInput;
        private readonly ValueInput? _toggleBushingSidesInput;
        private readonly ComboBox? _toggleLowerBushingShapeCombo;
        private readonly ComboBox? _toggleUpperBushingShapeCombo;
        private readonly ValueInput? _toggleLowerBushingRadiusScaleInput;
        private readonly ValueInput? _toggleLowerBushingHeightRatioInput;
        private readonly ValueInput? _toggleUpperBushingRadiusScaleInput;
        private readonly ValueInput? _toggleUpperBushingHeightRatioInput;
        private readonly ValueInput? _toggleUpperBushingKnurlAmountInput;
        private readonly ValueInput? _toggleUpperBushingKnurlDensityInput;
        private readonly ValueInput? _toggleUpperBushingKnurlDepthInput;
        private readonly ValueInput? _toggleUpperBushingAnisotropyStrengthInput;
        private readonly ValueInput? _toggleUpperBushingAnisotropyDensityInput;
        private readonly ValueInput? _toggleUpperBushingAnisotropyAngleInput;
        private readonly ValueInput? _toggleUpperBushingSurfaceCharacterInput;
        private readonly ValueInput? _togglePivotHousingRadiusInput;
        private readonly ValueInput? _togglePivotHousingDepthInput;
        private readonly ValueInput? _togglePivotHousingBevelInput;
        private readonly ValueInput? _togglePivotBallRadiusInput;
        private readonly ValueInput? _togglePivotClearanceInput;
        private readonly CheckBox? _toggleInvertBaseWindingCheckBox;
        private readonly CheckBox? _toggleInvertLeverWindingCheckBox;
        private readonly ValueInput? _toggleLeverLengthInput;
        private readonly ValueInput? _toggleLeverRadiusInput;
        private readonly ValueInput? _toggleLeverTopRadiusInput;
        private readonly ValueInput? _toggleLeverSidesInput;
        private readonly ValueInput? _toggleLeverPivotOffsetInput;
        private readonly ValueInput? _toggleTipRadiusInput;
        private readonly ValueInput? _toggleTipLatitudeSegmentsInput;
        private readonly ValueInput? _toggleTipLongitudeSegmentsInput;
        private readonly CheckBox? _toggleTipSleeveEnabledCheckBox;
        private readonly ValueInput? _toggleTipSleeveLengthInput;
        private readonly ValueInput? _toggleTipSleeveThicknessInput;
        private readonly ValueInput? _toggleTipSleeveOuterRadiusInput;
        private readonly ValueInput? _toggleTipSleeveCoverageInput;
        private readonly ValueInput? _toggleTipSleeveSidesInput;
        private readonly ComboBox? _toggleTipSleeveStyleCombo;
        private readonly ComboBox? _toggleTipSleeveTipStyleCombo;
        private readonly ValueInput? _toggleTipSleevePatternCountInput;
        private readonly ValueInput? _toggleTipSleevePatternDepthInput;
        private readonly ValueInput? _toggleTipSleeveTipAmountInput;
        private readonly ValueInput? _toggleTipSleeveColorRInput;
        private readonly ValueInput? _toggleTipSleeveColorGInput;
        private readonly ValueInput? _toggleTipSleeveColorBInput;
        private readonly ValueInput? _toggleTipSleeveMetallicInput;
        private readonly ValueInput? _toggleTipSleeveRoughnessInput;
        private readonly ValueInput? _toggleTipSleevePearlescenceInput;
        private readonly ValueInput? _toggleTipSleeveDiffuseStrengthInput;
        private readonly ValueInput? _toggleTipSleeveSpecularStrengthInput;
        private readonly ValueInput? _toggleTipSleeveRustInput;
        private readonly ValueInput? _toggleTipSleeveWearInput;
        private readonly ValueInput? _toggleTipSleeveGunkInput;
        private readonly ValueInput? _spiralRidgeHeightInput;
        private readonly ValueInput? _spiralRidgeWidthInput;
        private readonly ValueInput? _spiralTurnsInput;
        private readonly ComboBox? _gripStyleCombo;
        private readonly ComboBox? _gripTypeCombo;
        private readonly ValueInput? _gripStartInput;
        private readonly ValueInput? _gripHeightInput;
        private readonly ValueInput? _gripDensityInput;
        private readonly ValueInput? _gripPitchInput;
        private readonly ValueInput? _gripDepthInput;
        private readonly ValueInput? _gripWidthInput;
        private readonly ValueInput? _gripSharpnessInput;
            private readonly CheckBox? _collarEnabledCheckBox;
            private readonly ComboBox? _collarPresetCombo;
            private readonly Button? _refreshCollarLibraryButton;
            private readonly TextBox? _collarMeshPathTextBox;
        private readonly TextBlock? _collarResolvedMeshPathText;
        private readonly TextBlock? _collarMeshPathStatusText;
        private readonly ValueInput? _collarScaleInput;
        private readonly ValueInput? _collarBodyLengthInput;
        private readonly ValueInput? _collarBodyThicknessInput;
        private readonly ValueInput? _collarHeadLengthInput;
        private readonly ValueInput? _collarHeadThicknessInput;
        private readonly ValueInput? _collarRotateInput;
        private readonly CheckBox? _collarMirrorXCheckBox;
        private readonly CheckBox? _collarMirrorYCheckBox;
        private readonly CheckBox? _collarMirrorZCheckBox;
        private readonly ValueInput? _collarOffsetXInput;
        private readonly ValueInput? _collarOffsetYInput;
        private readonly ValueInput? _collarElevationInput;
        private readonly ValueInput? _collarInflateInput;
        private readonly ValueInput? _collarMaterialBaseRInput;
        private readonly ValueInput? _collarMaterialBaseGInput;
        private readonly ValueInput? _collarMaterialBaseBInput;
        private readonly ValueInput? _collarMaterialMetallicInput;
        private readonly ValueInput? _collarMaterialRoughnessInput;
        private readonly ValueInput? _collarMaterialPearlescenceInput;
        private readonly ValueInput? _collarMaterialRustInput;
        private readonly ValueInput? _collarMaterialWearInput;
        private readonly ValueInput? _collarMaterialGunkInput;
        private readonly CheckBox? _indicatorEnabledCheckBox;
        private readonly CheckBox? _indicatorCadWallsCheckBox;
        private readonly ComboBox? _indicatorShapeCombo;
        private readonly ComboBox? _indicatorReliefCombo;
        private readonly ComboBox? _indicatorProfileCombo;
        private readonly ValueInput? _indicatorWidthInput;
        private readonly ValueInput? _indicatorLengthInput;
        private readonly ValueInput? _indicatorPositionInput;
        private readonly ValueInput? _indicatorThicknessInput;
        private readonly ValueInput? _indicatorRoundnessInput;
        private readonly ValueInput? _indicatorColorBlendInput;
        private readonly ValueInput? _indicatorColorRInput;
        private readonly ValueInput? _indicatorColorGInput;
        private readonly ValueInput? _indicatorColorBInput;
        private readonly CheckBox? _indicatorAssemblyEnabledCheckBox;
        private readonly CheckBox? _indicatorQuickLightOnCheckBox;
        private readonly ValueInput? _indicatorQuickBrightnessInput;
        private readonly ValueInput? _indicatorQuickGlowInput;
        private readonly ValueInput? _indicatorBaseWidthInput;
        private readonly ValueInput? _indicatorBaseHeightInput;
        private readonly ValueInput? _indicatorBaseThicknessInput;
        private readonly ValueInput? _indicatorHousingRadiusInput;
        private readonly ValueInput? _indicatorHousingHeightInput;
        private readonly ValueInput? _indicatorLensRadiusInput;
        private readonly ValueInput? _indicatorLensHeightInput;
        private readonly ValueInput? _indicatorLensTransmissionInput;
        private readonly ValueInput? _indicatorLensIorInput;
        private readonly ValueInput? _indicatorLensThicknessInput;
        private readonly ValueInput? _indicatorLensAbsorptionInput;
        private readonly ValueInput? _indicatorLensSurfaceRoughnessInput;
        private readonly ValueInput? _indicatorLensSurfaceSpecularInput;
        private readonly ValueInput? _indicatorLensTintRInput;
        private readonly ValueInput? _indicatorLensTintGInput;
        private readonly ValueInput? _indicatorLensTintBInput;
        private readonly Button? _indicatorLensPresetClearButton;
        private readonly Button? _indicatorLensPresetFrostedButton;
        private readonly Button? _indicatorLensPresetSaturatedButton;
        private readonly ValueInput? _indicatorReflectorBaseRadiusInput;
        private readonly ValueInput? _indicatorReflectorTopRadiusInput;
        private readonly ValueInput? _indicatorReflectorDepthInput;
        private readonly ValueInput? _indicatorEmitterRadiusInput;
        private readonly ValueInput? _indicatorEmitterSpreadInput;
        private readonly ValueInput? _indicatorEmitterDepthInput;
        private readonly ValueInput? _indicatorEmitterCountInput;
        private readonly ValueInput? _indicatorRadialSegmentsInput;
        private readonly ValueInput? _indicatorLensLatitudeSegmentsInput;
        private readonly ValueInput? _indicatorLensLongitudeSegmentsInput;
        private readonly Button? _indicatorAssemblyResetDefaultsButton;
        private readonly CheckBox? _indicatorDynamicLightsEnabledCheckBox;
        private readonly ComboBox? _indicatorLightAnimationModeCombo;
        private readonly ValueInput? _indicatorLightAnimationSpeedInput;
        private readonly ValueInput? _indicatorLightFlickerAmountInput;
        private readonly ValueInput? _indicatorLightFlickerDropoutInput;
        private readonly ValueInput? _indicatorLightFlickerSmoothingInput;
        private readonly ValueInput? _indicatorLightFlickerSeedInput;
        private readonly Button? _indicatorLightPresetNeutralButton;
        private readonly Button? _indicatorLightPresetPulseButton;
        private readonly Button? _indicatorLightPresetFlickerButton;
        private readonly ComboBox? _indicatorEmitterSourceCombo;
        private readonly Button? _indicatorEmitterSourceMoveUpButton;
        private readonly Button? _indicatorEmitterSourceMoveDownButton;
        private readonly Button? _indicatorEmitterSourceAutoPhaseButton;
        private readonly TextBox? _indicatorEmitterSourceNameTextBox;
        private readonly CheckBox? _indicatorEmitterSourceEnabledCheckBox;
        private readonly ValueInput? _indicatorEmitterSourcePhaseOffsetInput;
        private readonly ValueInput? _indicatorEmitterSourceXInput;
        private readonly ValueInput? _indicatorEmitterSourceYInput;
        private readonly ValueInput? _indicatorEmitterSourceZInput;
        private readonly ValueInput? _indicatorEmitterSourceIntensityInput;
        private readonly ValueInput? _indicatorEmitterSourceRadiusInput;
        private readonly ValueInput? _indicatorEmitterSourceFalloffInput;
        private readonly ValueInput? _indicatorEmitterSourceRInput;
        private readonly ValueInput? _indicatorEmitterSourceGInput;
        private readonly ValueInput? _indicatorEmitterSourceBInput;
        private readonly ValueInput? _materialBaseRInput;
        private readonly ValueInput? _materialBaseGInput;
        private readonly ValueInput? _materialBaseBInput;
        private readonly StackPanel? _materialListPanel;
        private readonly ListBox? _materialListBox;
        private readonly TextBox? _materialNameTextBox;
        private readonly StackPanel? _materialRegionPanel;
        private readonly ComboBox? _materialRegionCombo;
        private readonly StackPanel? _assemblyMaterialPresetPanel;
        private readonly ComboBox? _assemblyMaterialPresetCombo;
        private readonly TextBlock? _assemblyMaterialPresetHintText;
        private readonly StackPanel? _materialManualControlsPanel;
        private readonly ValueInput? _materialMetallicInput;
        private readonly ValueInput? _materialRoughnessInput;
        private readonly ValueInput? _materialPearlescenceInput;
        private readonly ValueInput? _materialRustInput;
        private readonly ValueInput? _materialWearInput;
        private readonly ValueInput? _materialGunkInput;
        private readonly Button? _materialAlbedoMapBrowseButton;
        private readonly Button? _materialAlbedoMapClearButton;
        private readonly Button? _materialNormalMapBrowseButton;
        private readonly Button? _materialNormalMapClearButton;
        private readonly Button? _materialRoughnessMapBrowseButton;
        private readonly Button? _materialRoughnessMapClearButton;
        private readonly Button? _materialMetallicMapBrowseButton;
        private readonly Button? _materialMetallicMapClearButton;
        private readonly ValueInput? _materialNormalMapStrengthInput;
        private readonly ValueInput? _materialBrushStrengthInput;
        private readonly ValueInput? _materialBrushDensityInput;
        private readonly ValueInput? _materialCharacterInput;
        private readonly CheckBox? _spiralNormalInfluenceCheckBox;
        private readonly ComboBox? _basisDebugModeCombo;
        private readonly ValueInput? _microLodFadeStartInput;
        private readonly ValueInput? _microLodFadeEndInput;
        private readonly ValueInput? _microRoughnessLodBoostInput;
        private readonly ValueInput? _envIntensityInput;
        private readonly ValueInput? _envRoughnessMixInput;
        private readonly Button? _envIntensityResetButton;
        private readonly Button? _envRoughnessMixResetButton;
        private readonly ValueInput? _envTopRInput;
        private readonly ValueInput? _envTopGInput;
        private readonly ValueInput? _envTopBInput;
        private readonly ValueInput? _envBottomRInput;
        private readonly ValueInput? _envBottomGInput;
        private readonly ValueInput? _envBottomBInput;
        private readonly ComboBox? _envPresetCombo;
        private readonly ComboBox? _envTonemapCombo;
        private readonly ValueInput? _envExposureInput;
        private readonly ValueInput? _envBloomStrengthInput;
        private readonly ValueInput? _envBloomThresholdInput;
        private readonly ValueInput? _envBloomKneeInput;
        private readonly ComboBox? _envBloomKernelShapeCombo;
        private readonly StackPanel? _environmentManualSettingsPanel;
        private readonly TextBox? _envHdriPathTextBox;
        private readonly Button? _envHdriApplyButton;
        private readonly Button? _envHdriClearButton;
        private readonly ValueInput? _envHdriBlendInput;
        private readonly ValueInput? _envHdriRotationInput;
        private readonly CheckBox? _shadowEnabledCheckBox;
        private readonly ComboBox? _shadowSourceModeCombo;
        private readonly ValueInput? _shadowStrengthInput;
        private readonly ValueInput? _shadowSoftnessInput;
        private readonly ValueInput? _shadowDistanceInput;
        private readonly ValueInput? _shadowScaleInput;
        private readonly ValueInput? _shadowQualityInput;
        private readonly Button? _shadowStrengthResetButton;
        private readonly Button? _shadowSoftnessResetButton;
        private readonly Button? _shadowQualityResetButton;
        private readonly ValueInput? _shadowGrayInput;
        private readonly ValueInput? _shadowDiffuseInfluenceInput;
        private readonly CheckBox? _brushPaintEnabledCheckBox;
            private readonly ComboBox? _brushPaintChannelCombo;
            private readonly ComboBox? _brushTypeCombo;
            private readonly ColorPicker? _brushPaintColorPicker;
            private readonly StackPanel? _colorChannelPanel;
            private readonly StackPanel? _paintChannelTargetValuePanel;
            private readonly TextBlock? _paintChannelTargetValueLabel;
            private readonly ValueInput? _paintChannelTargetValueInput;
            private readonly TextBlock? _paintChannelTargetDisplayText;
            private readonly ListBox? _paintLayerListBox;
            private readonly TextBox? _paintLayerNameTextBox;
            private readonly Button? _addPaintLayerButton;
            private readonly Button? _renamePaintLayerButton;
            private readonly Button? _deletePaintLayerButton;
            private readonly CheckBox? _focusPaintLayerCheckBox;
            private readonly Button? _clearPaintLayerFocusButton;
            private readonly CheckBox? _paintLayerVisibleCheckBox;
            private readonly ComboBox? _paintLayerBlendModeCombo;
            private readonly ValueInput? _paintLayerOpacityInput;
            private readonly ComboBox? _paintMaskResolutionCombo;
            private readonly TextBlock? _paintMaskResolutionMemoryText;
            private readonly ComboBox? _scratchAbrasionTypeCombo;
            private readonly Border? _scratchContextBannerBorder;
            private readonly StackPanel? _scratchPrimaryPanel;
            private readonly StackPanel? _generalPaintPrimaryPanel;
            private readonly Expander? _brushAdvancedExpander;
            private readonly StackPanel? _generalPaintAdvancedPanel;
            private readonly StackPanel? _scratchAdvancedPanel;
            private readonly ValueInput? _brushSizeInput;
            private readonly ValueInput? _brushOpacityInput;
        private readonly ValueInput? _brushDarknessInput;
        private readonly ValueInput? _brushSpreadInput;
        private readonly ValueInput? _paintCoatMetallicInput;
        private readonly ValueInput? _paintCoatRoughnessInput;
        private readonly ValueInput? _clearCoatAmountInput;
        private readonly ValueInput? _clearCoatRoughnessInput;
        private readonly ValueInput? _anisotropyAngleInput;
        private readonly ValueInput? _scratchWidthInput;
        private readonly ValueInput? _scratchDepthInput;
        private readonly ValueInput? _scratchResistanceInput;
        private readonly ValueInput? _scratchDepthRampInput;
        private readonly ValueInput? _scratchExposeColorRInput;
        private readonly ValueInput? _scratchExposeColorGInput;
        private readonly ValueInput? _scratchExposeColorBInput;
        private readonly ValueInput? _scratchExposeMetallicInput;
        private readonly ValueInput? _scratchExposeRoughnessInput;
        private readonly Button? _clearPaintMaskButton;
        private readonly Button? _newProjectButton;
        private readonly Button? _changeProjectTypeButton;
        private readonly Button? _openProjectButton;
        private readonly Button? _saveProjectButton;
        private readonly Button? _saveProjectAsButton;
        private readonly Button? _renderButton;
        private readonly TextBlock? _topProjectStatusText;
        private readonly TextBlock? _contextStripNodeText;
        private readonly TextBlock? _contextStripToolText;
        private readonly TextBlock? _contextStripHintText;
        private readonly Popup? _brushDockPopup;
        private readonly Border? _viewportHostBorder;
        private readonly Border? _viewportBrushDock;
        private readonly Border? _brushDockDragHandle;
        private readonly Button? _brushQuickToggleButton;
        private readonly Button? _brushQuickColorButton;
        private readonly Button? _brushQuickScratchButton;
        private readonly Button? _brushQuickEraseButton;
        private readonly Button? _brushQuickRustButton;
        private readonly Button? _brushQuickWearButton;
        private readonly Button? _brushQuickGunkButton;
        private readonly Button? _brushQuickSprayButton;
        private readonly Button? _brushQuickStrokeButton;
        private readonly Button? _brushQuickNeedleButton;
        private readonly Button? _brushQuickScuffButton;
        private readonly Button? _brushQuickAddLayerButton;
        private readonly Button? _brushQuickClearMaskButton;
        private readonly TextBlock? _materialAlbedoMapPathText;
        private readonly TextBlock? _materialNormalMapPathText;
        private readonly TextBlock? _materialRoughnessMapPathText;
        private readonly TextBlock? _materialMetallicMapPathText;
        private readonly StackPanel? _materialNormalMapStrengthPanel;
            private readonly Button? _centerLightButton;
            private readonly ObservableCollection<SceneNode> _sceneNodes;
            private readonly ObservableCollection<MaterialInspectorListItem> _materialItems;
            private readonly List<UserReferenceProfile> _userReferenceProfiles = new();
            private readonly List<ReferenceStyleOption> _referenceStyleOptions = new();
            private readonly List<CollarPresetOption> _collarPresetOptions = new();
            private readonly List<SliderMeshOption> _sliderBackplateMeshOptions = new();
            private readonly List<SliderMeshOption> _sliderThumbMeshOptions = new();
            private readonly List<PushButtonMeshOption> _pushButtonBaseMeshOptions = new();
            private readonly List<PushButtonMeshOption> _pushButtonCapMeshOptions = new();
            private readonly List<ToggleMeshOption> _toggleBaseMeshOptions = new();
            private readonly List<ToggleMeshOption> _toggleLeverMeshOptions = new();
            private readonly List<MaterialRegionOption> _materialRegionOptions = new();
            private readonly List<AssemblyMaterialPresetOption> _assemblyMaterialPresetOptions = new();
            private readonly List<EnvironmentPresetOption> _environmentPresetOptions = new();
            private readonly List<BloomKernelShapeOption> _bloomKernelShapeOptions = new();
            private CollarPresetOption? _lastSelectableCollarPresetOption;
            private int _discoveredCollarLibraryCount;
            private readonly List<PaintLayerListItem> _paintLayerItems = new();
            private int _selectedMaterialIndex;
            private string? _selectedUserReferenceProfileName;
            private string? _currentProjectFilePath;
            private int _uiRefreshDepth;
            private bool _updatingUi;
            private bool _sceneRefreshDeferredPending;
            private bool _isBrushDockDragging;
            private Point _brushDockDragStart;
            private bool _brushDockHiddenByUser;
            private bool _brushDockDefaultPositionSet;

            private enum InspectorRefreshTabPolicy
            {
                PreserveCurrentTab = 0,
                FollowSceneSelection = 1
            }

            private sealed class MaterialInspectorListItem
            {
                public required string Name { get; init; }
                public required Guid MaterialId { get; init; }
                public required IBrush SwatchBrush { get; init; }
            }

            private sealed class AssemblyMaterialPresetOption
            {
                public required int Value { get; init; }
                public required string Name { get; init; }

                public override string ToString() => Name;
            }

            private sealed class MaterialRegionOption
            {
                public required MaterialRegionTarget Target { get; init; }
                public required string Name { get; init; }

                public override string ToString() => Name;
            }

            private sealed class EnvironmentPresetOption
            {
                public required EnvironmentPreset Preset { get; init; }
                public required string Name { get; init; }

                public override string ToString() => Name;
            }

            private sealed class BloomKernelShapeOption
            {
                public required BloomKernelShape Shape { get; init; }
                public required string Name { get; init; }

                public override string ToString() => Name;
            }

            private bool IsUiRefreshing => _uiRefreshDepth > 0;

        private void WithUiRefreshSuppressed(Action action)
        {
            _uiRefreshDepth++;
            _updatingUi = true;
            try
            {
                action();
            }
            finally
            {
                // IMPORTANT: delay turning off _updatingUi until after UI thread processes queued property events
                Dispatcher.UIThread.Post(() =>
                {
                    _uiRefreshDepth = Math.Max(0, _uiRefreshDepth - 1);
                    if (_uiRefreshDepth == 0)
                    {
                        _updatingUi = false;
                    }
                }, DispatcherPriority.Background);
            }
        }

        public MainWindow()
            : this(InteractorProjectType.RotaryKnob)
        {
        }

        public MainWindow(InteractorProjectType projectType)
        {
            InitializeComponent();
            _project = new KnobProject();
            _project.ApplyInteractorProjectTypeDefaults(projectType);
            _sceneNodes = new ObservableCollection<SceneNode>();
            _materialItems = new ObservableCollection<MaterialInspectorListItem>();

            _metalViewport = this.FindControl<MetalViewport>("MetalViewport");
            _viewportOverlay = this.FindControl<Control>("ViewportOverlay");
            _paintHudBorder = this.FindControl<Border>("PaintHudBorder");
            _paintHudTitleText = this.FindControl<TextBlock>("PaintHudTitleText");
            _paintHudLine1Text = this.FindControl<TextBlock>("PaintHudLine1Text");
            _paintHudLine2Text = this.FindControl<TextBlock>("PaintHudLine2Text");
            _paintHudLine3Text = this.FindControl<TextBlock>("PaintHudLine3Text");
            _paintHudLine4Text = this.FindControl<TextBlock>("PaintHudLine4Text");
            _sceneListBox = this.FindControl<ListBox>("SceneListBox");
            _inspectorTabControl = this.FindControl<TabControl>("InspectorTabControl");
            _lightingTabItem = this.FindControl<TabItem>("LightingTabItem");
            _modelTabItem = this.FindControl<TabItem>("ModelTabItem");
            _nodeInspectorContextText = this.FindControl<TextBlock>("NodeInspectorContextText");
            _nodeReferenceProfilesExpander = this.FindControl<Expander>("NodeReferenceProfilesExpander");
            _nodeTransformExpander = this.FindControl<Expander>("NodeTransformExpander");
            _nodeBodyShapeExpander = this.FindControl<Expander>("NodeBodyShapeExpander");
            _nodeSliderAssemblyExpander = this.FindControl<Expander>("NodeSliderAssemblyExpander");
            _nodeToggleAssemblyExpander = this.FindControl<Expander>("NodeToggleAssemblyExpander");
            _nodePushButtonAssemblyExpander = this.FindControl<Expander>("NodePushButtonAssemblyExpander");
            _nodeSpiralRidgeExpander = this.FindControl<Expander>("NodeSpiralRidgeExpander");
            _nodeGripExpander = this.FindControl<Expander>("NodeGripExpander");
            _nodeCollarExpander = this.FindControl<Expander>("NodeCollarExpander");
            _nodeRotaryIndicatorExpander = this.FindControl<Expander>("NodeRotaryIndicatorExpander");
            _nodeIndicatorLightAssemblyExpander = this.FindControl<Expander>("NodeIndicatorLightAssemblyExpander");
            _nodeMaterialExpander = this.FindControl<Expander>("NodeMaterialExpander");
            _nodeSurfaceTextureExpander = this.FindControl<Expander>("NodeSurfaceTextureExpander");
            _nodeMicroDetailExpander = this.FindControl<Expander>("NodeMicroDetailExpander");
            _brushTabItem = this.FindControl<TabItem>("BrushTabItem");
            _sceneTabItem = this.FindControl<TabItem>("SceneTabItem");
            _shadowsTabItem = this.FindControl<TabItem>("ShadowsTabItem");
            _materialGraphTabItem = this.FindControl<TabItem>("MaterialGraphTabItem");
            _graphEnabledCheckBox = this.FindControl<CheckBox>("GraphEnabledCheckBox");
            _graphValidationText = this.FindControl<TextBlock>("GraphValidationText");
            _graphNodeListBox = this.FindControl<ListBox>("GraphNodeListBox");
            _addNodeTypeCombo = this.FindControl<ComboBox>("AddNodeTypeCombo");
            _addNodeButton = this.FindControl<Button>("AddNodeButton");
            _removeNodeButton = this.FindControl<Button>("RemoveNodeButton");
            _nodePropertiesExpander = this.FindControl<Expander>("NodePropertiesExpander");
            _nodePropertiesPanel = this.FindControl<StackPanel>("NodePropertiesPanel");
            _graphConnectionListBox = this.FindControl<ListBox>("GraphConnectionListBox");
            _addConnectionButton = this.FindControl<Button>("AddConnectionButton");
            _removeConnectionButton = this.FindControl<Button>("RemoveConnectionButton");
            _graphPreviewBakeButton = this.FindControl<Button>("GraphPreviewBakeButton");
            _graphPreviewImage = this.FindControl<Image>("GraphPreviewImage");
            _undoButton = this.FindControl<Button>("UndoButton");
            _redoButton = this.FindControl<Button>("RedoButton");
            _inspectorScrollViewer = this.FindControl<ScrollViewer>("InspectorScrollViewer");
            _inspectorSearchTextBox = this.FindControl<TextBox>("InspectorSearchTextBox");
            _runtimeDiagnosticsText = this.FindControl<TextBlock>("RuntimeDiagnosticsText");
            _inspectorSearchResultsListBox = this.FindControl<ListBox>("InspectorSearchResultsListBox");
            _recentTweaksListBox = this.FindControl<ListBox>("RecentTweaksListBox");
            _favoriteReferenceProfilesButton = this.FindControl<Button>("FavoriteReferenceProfilesButton");
            _favoriteRoughnessButton = this.FindControl<Button>("FavoriteRoughnessButton");
            _favoriteScratchDepthButton = this.FindControl<Button>("FavoriteScratchDepthButton");
            _favoriteCollarPresetButton = this.FindControl<Button>("FavoriteCollarPresetButton");
            _favoriteShadowSoftnessButton = this.FindControl<Button>("FavoriteShadowSoftnessButton");
            _favoriteEnvIntensityButton = this.FindControl<Button>("FavoriteEnvIntensityButton");
            _lightingModeCombo = this.FindControl<ComboBox>("LightingModeCombo");
            _lightListBox = this.FindControl<ListBox>("LightListBox");
            _addLightButton = this.FindControl<Button>("AddLightButton");
            _removeLightButton = this.FindControl<Button>("RemoveLightButton");
            _resetViewButton = this.FindControl<Button>("ResetViewButton");
            _lightTypeCombo = this.FindControl<ComboBox>("LightTypeCombo");
            _rotationInput = this.FindControl<ValueInput>("RotationInput");
            _lightXInput = this.FindControl<ValueInput>("LightXInput");
            _lightYInput = this.FindControl<ValueInput>("LightYInput");
            _lightZInput = this.FindControl<ValueInput>("LightZInput");
            _directionInput = this.FindControl<ValueInput>("DirectionInput");
            _intensityInput = this.FindControl<ValueInput>("IntensityInput");
            _falloffInput = this.FindControl<ValueInput>("FalloffInput");
            _lightRInput = this.FindControl<ValueInput>("LightRInput");
            _lightGInput = this.FindControl<ValueInput>("LightGInput");
            _lightBInput = this.FindControl<ValueInput>("LightBInput");
            _diffuseBoostInput = this.FindControl<ValueInput>("DiffuseBoostInput");
            _specularBoostInput = this.FindControl<ValueInput>("SpecularBoostInput");
            _specularPowerInput = this.FindControl<ValueInput>("SpecularPowerInput");
            _modelRadiusInput = this.FindControl<ValueInput>("ModelRadiusInput");
            _modelHeightInput = this.FindControl<ValueInput>("ModelHeightInput");
            _modelTopScaleInput = this.FindControl<ValueInput>("ModelTopScaleInput");
            _modelBevelInput = this.FindControl<ValueInput>("ModelBevelInput");
            _referenceStyleCombo = this.FindControl<ComboBox>("ReferenceStyleCombo");
            _referenceStyleSaveNameTextBox = this.FindControl<TextBox>("ReferenceStyleSaveNameTextBox");
            _saveReferenceProfileButton = this.FindControl<Button>("SaveReferenceProfileButton");
            _overwriteReferenceProfileButton = this.FindControl<Button>("OverwriteReferenceProfileButton");
            _renameReferenceProfileButton = this.FindControl<Button>("RenameReferenceProfileButton");
            _duplicateReferenceProfileButton = this.FindControl<Button>("DuplicateReferenceProfileButton");
            _deleteReferenceProfileButton = this.FindControl<Button>("DeleteReferenceProfileButton");
            _referenceProfileStatusText = this.FindControl<TextBlock>("ReferenceProfileStatusText");
            _bodyStyleCombo = this.FindControl<ComboBox>("BodyStyleCombo");
            _bevelCurveInput = this.FindControl<ValueInput>("BevelCurveInput");
            _crownProfileInput = this.FindControl<ValueInput>("CrownProfileInput");
            _bodyTaperInput = this.FindControl<ValueInput>("BodyTaperInput");
            _bodyBulgeInput = this.FindControl<ValueInput>("BodyBulgeInput");
            _modelSegmentsInput = this.FindControl<ValueInput>("ModelSegmentsInput");
            _sliderAssemblyModeCombo = this.FindControl<ComboBox>("SliderAssemblyModeCombo");
            _refreshSliderLibraryButton = this.FindControl<Button>("RefreshSliderLibraryButton");
            _sliderBackplateMeshCombo = this.FindControl<ComboBox>("SliderBackplateMeshCombo");
            _sliderThumbMeshCombo = this.FindControl<ComboBox>("SliderThumbMeshCombo");
            _sliderThumbProfileCombo = this.FindControl<ComboBox>("SliderThumbProfileCombo");
            _sliderTrackStyleCombo = this.FindControl<ComboBox>("SliderTrackStyleCombo");
            _sliderBackplateWidthInput = this.FindControl<ValueInput>("SliderBackplateWidthInput");
            _sliderBackplateHeightInput = this.FindControl<ValueInput>("SliderBackplateHeightInput");
            _sliderBackplateThicknessInput = this.FindControl<ValueInput>("SliderBackplateThicknessInput");
            _sliderThumbWidthInput = this.FindControl<ValueInput>("SliderThumbWidthInput");
            _sliderThumbHeightInput = this.FindControl<ValueInput>("SliderThumbHeightInput");
            _sliderThumbDepthInput = this.FindControl<ValueInput>("SliderThumbDepthInput");
            _sliderTrackWidthInput = this.FindControl<ValueInput>("SliderTrackWidthInput");
            _sliderTrackDepthInput = this.FindControl<ValueInput>("SliderTrackDepthInput");
            _sliderRailHeightInput = this.FindControl<ValueInput>("SliderRailHeightInput");
            _sliderRailSpacingInput = this.FindControl<ValueInput>("SliderRailSpacingInput");
            _sliderThumbRidgeCountInput = this.FindControl<ValueInput>("SliderThumbRidgeCountInput");
            _sliderThumbRidgeDepthInput = this.FindControl<ValueInput>("SliderThumbRidgeDepthInput");
            _sliderThumbCornerRadiusInput = this.FindControl<ValueInput>("SliderThumbCornerRadiusInput");
            _refreshPushButtonLibraryButton = this.FindControl<Button>("RefreshPushButtonLibraryButton");
            _pushButtonBaseMeshCombo = this.FindControl<ComboBox>("PushButtonBaseMeshCombo");
            _pushButtonCapMeshCombo = this.FindControl<ComboBox>("PushButtonCapMeshCombo");
            _pushButtonCapProfileCombo = this.FindControl<ComboBox>("PushButtonCapProfileCombo");
            _pushButtonBezelProfileCombo = this.FindControl<ComboBox>("PushButtonBezelProfileCombo");
            _pushButtonSkirtStyleCombo = this.FindControl<ComboBox>("PushButtonSkirtStyleCombo");
            _pushButtonPressAmountInput = this.FindControl<ValueInput>("PushButtonPressAmountInput");
            _pushButtonBezelChamferSizeInput = this.FindControl<ValueInput>("PushButtonBezelChamferSizeInput");
            _pushButtonCapOverhangInput = this.FindControl<ValueInput>("PushButtonCapOverhangInput");
            _pushButtonCapSegmentsInput = this.FindControl<ValueInput>("PushButtonCapSegmentsInput");
            _pushButtonBezelSegmentsInput = this.FindControl<ValueInput>("PushButtonBezelSegmentsInput");
            _pushButtonSkirtHeightInput = this.FindControl<ValueInput>("PushButtonSkirtHeightInput");
            _pushButtonSkirtRadiusInput = this.FindControl<ValueInput>("PushButtonSkirtRadiusInput");
            _toggleAssemblyModeCombo = this.FindControl<ComboBox>("ToggleAssemblyModeCombo");
            _refreshToggleLibraryButton = this.FindControl<Button>("RefreshToggleLibraryButton");
            _toggleBaseMeshCombo = this.FindControl<ComboBox>("ToggleBaseMeshCombo");
            _toggleLeverMeshCombo = this.FindControl<ComboBox>("ToggleLeverMeshCombo");
            _toggleStateCountCombo = this.FindControl<ComboBox>("ToggleStateCountCombo");
            _toggleStateIndexInput = this.FindControl<ValueInput>("ToggleStateIndexInput");
            _toggleMaxAngleInput = this.FindControl<ValueInput>("ToggleMaxAngleInput");
            _togglePlateWidthInput = this.FindControl<ValueInput>("TogglePlateWidthInput");
            _togglePlateHeightInput = this.FindControl<ValueInput>("TogglePlateHeightInput");
            _togglePlateThicknessInput = this.FindControl<ValueInput>("TogglePlateThicknessInput");
            _togglePlateOffsetYInput = this.FindControl<ValueInput>("TogglePlateOffsetYInput");
            _togglePlateOffsetZInput = this.FindControl<ValueInput>("TogglePlateOffsetZInput");
            _toggleBushingRadiusInput = this.FindControl<ValueInput>("ToggleBushingRadiusInput");
            _toggleBushingHeightInput = this.FindControl<ValueInput>("ToggleBushingHeightInput");
            _toggleBushingSidesInput = this.FindControl<ValueInput>("ToggleBushingSidesInput");
            _toggleLowerBushingShapeCombo = this.FindControl<ComboBox>("ToggleLowerBushingShapeCombo");
            _toggleUpperBushingShapeCombo = this.FindControl<ComboBox>("ToggleUpperBushingShapeCombo");
            _toggleLowerBushingRadiusScaleInput = this.FindControl<ValueInput>("ToggleLowerBushingRadiusScaleInput");
            _toggleLowerBushingHeightRatioInput = this.FindControl<ValueInput>("ToggleLowerBushingHeightRatioInput");
            _toggleUpperBushingRadiusScaleInput = this.FindControl<ValueInput>("ToggleUpperBushingRadiusScaleInput");
            _toggleUpperBushingHeightRatioInput = this.FindControl<ValueInput>("ToggleUpperBushingHeightRatioInput");
            _toggleUpperBushingKnurlAmountInput = this.FindControl<ValueInput>("ToggleUpperBushingKnurlAmountInput");
            _toggleUpperBushingKnurlDensityInput = this.FindControl<ValueInput>("ToggleUpperBushingKnurlDensityInput");
            _toggleUpperBushingKnurlDepthInput = this.FindControl<ValueInput>("ToggleUpperBushingKnurlDepthInput");
            _toggleUpperBushingAnisotropyStrengthInput = this.FindControl<ValueInput>("ToggleUpperBushingAnisotropyStrengthInput");
            _toggleUpperBushingAnisotropyDensityInput = this.FindControl<ValueInput>("ToggleUpperBushingAnisotropyDensityInput");
            _toggleUpperBushingAnisotropyAngleInput = this.FindControl<ValueInput>("ToggleUpperBushingAnisotropyAngleInput");
            _toggleUpperBushingSurfaceCharacterInput = this.FindControl<ValueInput>("ToggleUpperBushingSurfaceCharacterInput");
            _togglePivotHousingRadiusInput = this.FindControl<ValueInput>("TogglePivotHousingRadiusInput");
            _togglePivotHousingDepthInput = this.FindControl<ValueInput>("TogglePivotHousingDepthInput");
            _togglePivotHousingBevelInput = this.FindControl<ValueInput>("TogglePivotHousingBevelInput");
            _togglePivotBallRadiusInput = this.FindControl<ValueInput>("TogglePivotBallRadiusInput");
            _togglePivotClearanceInput = this.FindControl<ValueInput>("TogglePivotClearanceInput");
            _toggleInvertBaseWindingCheckBox = this.FindControl<CheckBox>("ToggleInvertBaseWindingCheckBox");
            _toggleInvertLeverWindingCheckBox = this.FindControl<CheckBox>("ToggleInvertLeverWindingCheckBox");
            _toggleLeverLengthInput = this.FindControl<ValueInput>("ToggleLeverLengthInput");
            _toggleLeverRadiusInput = this.FindControl<ValueInput>("ToggleLeverRadiusInput");
            _toggleLeverTopRadiusInput = this.FindControl<ValueInput>("ToggleLeverTopRadiusInput");
            _toggleLeverSidesInput = this.FindControl<ValueInput>("ToggleLeverSidesInput");
            _toggleLeverPivotOffsetInput = this.FindControl<ValueInput>("ToggleLeverPivotOffsetInput");
            _toggleTipRadiusInput = this.FindControl<ValueInput>("ToggleTipRadiusInput");
            _toggleTipLatitudeSegmentsInput = this.FindControl<ValueInput>("ToggleTipLatitudeSegmentsInput");
            _toggleTipLongitudeSegmentsInput = this.FindControl<ValueInput>("ToggleTipLongitudeSegmentsInput");
            _toggleTipSleeveEnabledCheckBox = this.FindControl<CheckBox>("ToggleTipSleeveEnabledCheckBox");
            _toggleTipSleeveLengthInput = this.FindControl<ValueInput>("ToggleTipSleeveLengthInput");
            _toggleTipSleeveThicknessInput = this.FindControl<ValueInput>("ToggleTipSleeveThicknessInput");
            _toggleTipSleeveOuterRadiusInput = this.FindControl<ValueInput>("ToggleTipSleeveOuterRadiusInput");
            _toggleTipSleeveCoverageInput = this.FindControl<ValueInput>("ToggleTipSleeveCoverageInput");
            _toggleTipSleeveSidesInput = this.FindControl<ValueInput>("ToggleTipSleeveSidesInput");
            _toggleTipSleeveStyleCombo = this.FindControl<ComboBox>("ToggleTipSleeveStyleCombo");
            _toggleTipSleeveTipStyleCombo = this.FindControl<ComboBox>("ToggleTipSleeveTipStyleCombo");
            _toggleTipSleevePatternCountInput = this.FindControl<ValueInput>("ToggleTipSleevePatternCountInput");
            _toggleTipSleevePatternDepthInput = this.FindControl<ValueInput>("ToggleTipSleevePatternDepthInput");
            _toggleTipSleeveTipAmountInput = this.FindControl<ValueInput>("ToggleTipSleeveTipAmountInput");
            _toggleTipSleeveColorRInput = this.FindControl<ValueInput>("ToggleTipSleeveColorRInput");
            _toggleTipSleeveColorGInput = this.FindControl<ValueInput>("ToggleTipSleeveColorGInput");
            _toggleTipSleeveColorBInput = this.FindControl<ValueInput>("ToggleTipSleeveColorBInput");
            _toggleTipSleeveMetallicInput = this.FindControl<ValueInput>("ToggleTipSleeveMetallicInput");
            _toggleTipSleeveRoughnessInput = this.FindControl<ValueInput>("ToggleTipSleeveRoughnessInput");
            _toggleTipSleevePearlescenceInput = this.FindControl<ValueInput>("ToggleTipSleevePearlescenceInput");
            _toggleTipSleeveDiffuseStrengthInput = this.FindControl<ValueInput>("ToggleTipSleeveDiffuseStrengthInput");
            _toggleTipSleeveSpecularStrengthInput = this.FindControl<ValueInput>("ToggleTipSleeveSpecularStrengthInput");
            _toggleTipSleeveRustInput = this.FindControl<ValueInput>("ToggleTipSleeveRustInput");
            _toggleTipSleeveWearInput = this.FindControl<ValueInput>("ToggleTipSleeveWearInput");
            _toggleTipSleeveGunkInput = this.FindControl<ValueInput>("ToggleTipSleeveGunkInput");
            _spiralRidgeHeightInput = this.FindControl<ValueInput>("SpiralRidgeHeightInput");
            _spiralRidgeWidthInput = this.FindControl<ValueInput>("SpiralRidgeWidthInput");
            _spiralTurnsInput = this.FindControl<ValueInput>("SpiralTurnsInput");
            _gripStyleCombo = this.FindControl<ComboBox>("GripStyleCombo");
            _gripTypeCombo = this.FindControl<ComboBox>("GripTypeCombo");
            _gripStartInput = this.FindControl<ValueInput>("GripStartInput");
            _gripHeightInput = this.FindControl<ValueInput>("GripHeightInput");
            _gripDensityInput = this.FindControl<ValueInput>("GripDensityInput");
            _gripPitchInput = this.FindControl<ValueInput>("GripPitchInput");
            _gripDepthInput = this.FindControl<ValueInput>("GripDepthInput");
            _gripWidthInput = this.FindControl<ValueInput>("GripWidthInput");
            _gripSharpnessInput = this.FindControl<ValueInput>("GripSharpnessInput");
            _collarEnabledCheckBox = this.FindControl<CheckBox>("CollarEnabledCheckBox");
            _collarPresetCombo = this.FindControl<ComboBox>("CollarPresetCombo");
            _refreshCollarLibraryButton = this.FindControl<Button>("RefreshCollarLibraryButton");
            _collarMeshPathTextBox = this.FindControl<TextBox>("CollarMeshPathTextBox");
            _collarResolvedMeshPathText = this.FindControl<TextBlock>("CollarResolvedMeshPathText");
            _collarMeshPathStatusText = this.FindControl<TextBlock>("CollarMeshPathStatusText");
            _collarScaleInput = this.FindControl<ValueInput>("CollarScaleInput");
            _collarBodyLengthInput = this.FindControl<ValueInput>("CollarBodyLengthInput");
            _collarBodyThicknessInput = this.FindControl<ValueInput>("CollarBodyThicknessInput");
            _collarHeadLengthInput = this.FindControl<ValueInput>("CollarHeadLengthInput");
            _collarHeadThicknessInput = this.FindControl<ValueInput>("CollarHeadThicknessInput");
            _collarRotateInput = this.FindControl<ValueInput>("CollarRotateInput");
            _collarMirrorXCheckBox = this.FindControl<CheckBox>("CollarMirrorXCheckBox");
            _collarMirrorYCheckBox = this.FindControl<CheckBox>("CollarMirrorYCheckBox");
            _collarMirrorZCheckBox = this.FindControl<CheckBox>("CollarMirrorZCheckBox");
            _collarOffsetXInput = this.FindControl<ValueInput>("CollarOffsetXInput");
            _collarOffsetYInput = this.FindControl<ValueInput>("CollarOffsetYInput");
            _collarElevationInput = this.FindControl<ValueInput>("CollarElevationInput");
            _collarInflateInput = this.FindControl<ValueInput>("CollarInflateInput");
            _collarMaterialBaseRInput = this.FindControl<ValueInput>("CollarMaterialBaseRInput");
            _collarMaterialBaseGInput = this.FindControl<ValueInput>("CollarMaterialBaseGInput");
            _collarMaterialBaseBInput = this.FindControl<ValueInput>("CollarMaterialBaseBInput");
            _collarMaterialMetallicInput = this.FindControl<ValueInput>("CollarMaterialMetallicInput");
            _collarMaterialRoughnessInput = this.FindControl<ValueInput>("CollarMaterialRoughnessInput");
            _collarMaterialPearlescenceInput = this.FindControl<ValueInput>("CollarMaterialPearlescenceInput");
            _collarMaterialRustInput = this.FindControl<ValueInput>("CollarMaterialRustInput");
            _collarMaterialWearInput = this.FindControl<ValueInput>("CollarMaterialWearInput");
            _collarMaterialGunkInput = this.FindControl<ValueInput>("CollarMaterialGunkInput");
            _indicatorEnabledCheckBox = this.FindControl<CheckBox>("IndicatorEnabledCheckBox");
            _indicatorCadWallsCheckBox = this.FindControl<CheckBox>("IndicatorCadWallsCheckBox");
            _indicatorShapeCombo = this.FindControl<ComboBox>("IndicatorShapeCombo");
            _indicatorReliefCombo = this.FindControl<ComboBox>("IndicatorReliefCombo");
            _indicatorProfileCombo = this.FindControl<ComboBox>("IndicatorProfileCombo");
            _indicatorWidthInput = this.FindControl<ValueInput>("IndicatorWidthInput");
            _indicatorLengthInput = this.FindControl<ValueInput>("IndicatorLengthInput");
            _indicatorPositionInput = this.FindControl<ValueInput>("IndicatorPositionInput");
            _indicatorThicknessInput = this.FindControl<ValueInput>("IndicatorThicknessInput");
            _indicatorRoundnessInput = this.FindControl<ValueInput>("IndicatorRoundnessInput");
            _indicatorColorBlendInput = this.FindControl<ValueInput>("IndicatorColorBlendInput");
            _indicatorColorRInput = this.FindControl<ValueInput>("IndicatorColorRInput");
            _indicatorColorGInput = this.FindControl<ValueInput>("IndicatorColorGInput");
            _indicatorColorBInput = this.FindControl<ValueInput>("IndicatorColorBInput");
            _indicatorAssemblyEnabledCheckBox = this.FindControl<CheckBox>("IndicatorAssemblyEnabledCheckBox");
            _indicatorQuickLightOnCheckBox = this.FindControl<CheckBox>("IndicatorQuickLightOnCheckBox");
            _indicatorQuickBrightnessInput = this.FindControl<ValueInput>("IndicatorQuickBrightnessInput");
            _indicatorQuickGlowInput = this.FindControl<ValueInput>("IndicatorQuickGlowInput");
            _indicatorBaseWidthInput = this.FindControl<ValueInput>("IndicatorBaseWidthInput");
            _indicatorBaseHeightInput = this.FindControl<ValueInput>("IndicatorBaseHeightInput");
            _indicatorBaseThicknessInput = this.FindControl<ValueInput>("IndicatorBaseThicknessInput");
            _indicatorHousingRadiusInput = this.FindControl<ValueInput>("IndicatorHousingRadiusInput");
            _indicatorHousingHeightInput = this.FindControl<ValueInput>("IndicatorHousingHeightInput");
            _indicatorLensRadiusInput = this.FindControl<ValueInput>("IndicatorLensRadiusInput");
            _indicatorLensHeightInput = this.FindControl<ValueInput>("IndicatorLensHeightInput");
            _indicatorLensTransmissionInput = this.FindControl<ValueInput>("IndicatorLensTransmissionInput");
            _indicatorLensIorInput = this.FindControl<ValueInput>("IndicatorLensIorInput");
            _indicatorLensThicknessInput = this.FindControl<ValueInput>("IndicatorLensThicknessInput");
            _indicatorLensAbsorptionInput = this.FindControl<ValueInput>("IndicatorLensAbsorptionInput");
            _indicatorLensSurfaceRoughnessInput = this.FindControl<ValueInput>("IndicatorLensSurfaceRoughnessInput");
            _indicatorLensSurfaceSpecularInput = this.FindControl<ValueInput>("IndicatorLensSurfaceSpecularInput");
            _indicatorLensTintRInput = this.FindControl<ValueInput>("IndicatorLensTintRInput");
            _indicatorLensTintGInput = this.FindControl<ValueInput>("IndicatorLensTintGInput");
            _indicatorLensTintBInput = this.FindControl<ValueInput>("IndicatorLensTintBInput");
            _indicatorLensPresetClearButton = this.FindControl<Button>("IndicatorLensPresetClearButton");
            _indicatorLensPresetFrostedButton = this.FindControl<Button>("IndicatorLensPresetFrostedButton");
            _indicatorLensPresetSaturatedButton = this.FindControl<Button>("IndicatorLensPresetSaturatedButton");
            _indicatorReflectorBaseRadiusInput = this.FindControl<ValueInput>("IndicatorReflectorBaseRadiusInput");
            _indicatorReflectorTopRadiusInput = this.FindControl<ValueInput>("IndicatorReflectorTopRadiusInput");
            _indicatorReflectorDepthInput = this.FindControl<ValueInput>("IndicatorReflectorDepthInput");
            _indicatorEmitterRadiusInput = this.FindControl<ValueInput>("IndicatorEmitterRadiusInput");
            _indicatorEmitterSpreadInput = this.FindControl<ValueInput>("IndicatorEmitterSpreadInput");
            _indicatorEmitterDepthInput = this.FindControl<ValueInput>("IndicatorEmitterDepthInput");
            _indicatorEmitterCountInput = this.FindControl<ValueInput>("IndicatorEmitterCountInput");
            _indicatorRadialSegmentsInput = this.FindControl<ValueInput>("IndicatorRadialSegmentsInput");
            _indicatorLensLatitudeSegmentsInput = this.FindControl<ValueInput>("IndicatorLensLatitudeSegmentsInput");
            _indicatorLensLongitudeSegmentsInput = this.FindControl<ValueInput>("IndicatorLensLongitudeSegmentsInput");
            _indicatorAssemblyResetDefaultsButton = this.FindControl<Button>("IndicatorAssemblyResetDefaultsButton");
            _indicatorDynamicLightsEnabledCheckBox = this.FindControl<CheckBox>("IndicatorDynamicLightsEnabledCheckBox");
            _indicatorLightAnimationModeCombo = this.FindControl<ComboBox>("IndicatorLightAnimationModeCombo");
            _indicatorLightAnimationSpeedInput = this.FindControl<ValueInput>("IndicatorLightAnimationSpeedInput");
            _indicatorLightFlickerAmountInput = this.FindControl<ValueInput>("IndicatorLightFlickerAmountInput");
            _indicatorLightFlickerDropoutInput = this.FindControl<ValueInput>("IndicatorLightFlickerDropoutInput");
            _indicatorLightFlickerSmoothingInput = this.FindControl<ValueInput>("IndicatorLightFlickerSmoothingInput");
            _indicatorLightFlickerSeedInput = this.FindControl<ValueInput>("IndicatorLightFlickerSeedInput");
            _indicatorLightPresetNeutralButton = this.FindControl<Button>("IndicatorLightPresetNeutralButton");
            _indicatorLightPresetPulseButton = this.FindControl<Button>("IndicatorLightPresetPulseButton");
            _indicatorLightPresetFlickerButton = this.FindControl<Button>("IndicatorLightPresetFlickerButton");
            _indicatorEmitterSourceCombo = this.FindControl<ComboBox>("IndicatorEmitterSourceCombo");
            _indicatorEmitterSourceMoveUpButton = this.FindControl<Button>("IndicatorEmitterSourceMoveUpButton");
            _indicatorEmitterSourceMoveDownButton = this.FindControl<Button>("IndicatorEmitterSourceMoveDownButton");
            _indicatorEmitterSourceAutoPhaseButton = this.FindControl<Button>("IndicatorEmitterSourceAutoPhaseButton");
            _indicatorEmitterSourceNameTextBox = this.FindControl<TextBox>("IndicatorEmitterSourceNameTextBox");
            _indicatorEmitterSourceEnabledCheckBox = this.FindControl<CheckBox>("IndicatorEmitterSourceEnabledCheckBox");
            _indicatorEmitterSourcePhaseOffsetInput = this.FindControl<ValueInput>("IndicatorEmitterSourcePhaseOffsetInput");
            _indicatorEmitterSourceXInput = this.FindControl<ValueInput>("IndicatorEmitterSourceXInput");
            _indicatorEmitterSourceYInput = this.FindControl<ValueInput>("IndicatorEmitterSourceYInput");
            _indicatorEmitterSourceZInput = this.FindControl<ValueInput>("IndicatorEmitterSourceZInput");
            _indicatorEmitterSourceIntensityInput = this.FindControl<ValueInput>("IndicatorEmitterSourceIntensityInput");
            _indicatorEmitterSourceRadiusInput = this.FindControl<ValueInput>("IndicatorEmitterSourceRadiusInput");
            _indicatorEmitterSourceFalloffInput = this.FindControl<ValueInput>("IndicatorEmitterSourceFalloffInput");
            _indicatorEmitterSourceRInput = this.FindControl<ValueInput>("IndicatorEmitterSourceRInput");
            _indicatorEmitterSourceGInput = this.FindControl<ValueInput>("IndicatorEmitterSourceGInput");
            _indicatorEmitterSourceBInput = this.FindControl<ValueInput>("IndicatorEmitterSourceBInput");
            _materialBaseRInput = this.FindControl<ValueInput>("MaterialBaseRInput");
            _materialBaseGInput = this.FindControl<ValueInput>("MaterialBaseGInput");
            _materialBaseBInput = this.FindControl<ValueInput>("MaterialBaseBInput");
            _materialListPanel = this.FindControl<StackPanel>("MaterialListPanel");
            _materialListBox = this.FindControl<ListBox>("MaterialListBox");
            _materialNameTextBox = this.FindControl<TextBox>("MaterialNameTextBox");
            _materialRegionPanel = this.FindControl<StackPanel>("MaterialRegionPanel");
            _materialRegionCombo = this.FindControl<ComboBox>("MaterialRegionCombo");
            _assemblyMaterialPresetPanel = this.FindControl<StackPanel>("AssemblyMaterialPresetPanel");
            _assemblyMaterialPresetCombo = this.FindControl<ComboBox>("AssemblyMaterialPresetCombo");
            _assemblyMaterialPresetHintText = this.FindControl<TextBlock>("AssemblyMaterialPresetHintText");
            _materialManualControlsPanel = this.FindControl<StackPanel>("MaterialManualControlsPanel");
            _materialMetallicInput = this.FindControl<ValueInput>("MaterialMetallicInput");
            _materialRoughnessInput = this.FindControl<ValueInput>("MaterialRoughnessInput");
            _materialPearlescenceInput = this.FindControl<ValueInput>("MaterialPearlescenceInput");
            _materialRustInput = this.FindControl<ValueInput>("MaterialRustInput");
            _materialWearInput = this.FindControl<ValueInput>("MaterialWearInput");
            _materialGunkInput = this.FindControl<ValueInput>("MaterialGunkInput");
            _materialAlbedoMapBrowseButton = this.FindControl<Button>("MaterialAlbedoMapBrowseButton");
            _materialAlbedoMapClearButton = this.FindControl<Button>("MaterialAlbedoMapClearButton");
            _materialNormalMapBrowseButton = this.FindControl<Button>("MaterialNormalMapBrowseButton");
            _materialNormalMapClearButton = this.FindControl<Button>("MaterialNormalMapClearButton");
            _materialRoughnessMapBrowseButton = this.FindControl<Button>("MaterialRoughnessMapBrowseButton");
            _materialRoughnessMapClearButton = this.FindControl<Button>("MaterialRoughnessMapClearButton");
            _materialMetallicMapBrowseButton = this.FindControl<Button>("MaterialMetallicMapBrowseButton");
            _materialMetallicMapClearButton = this.FindControl<Button>("MaterialMetallicMapClearButton");
            _materialNormalMapStrengthInput = this.FindControl<ValueInput>("MaterialNormalMapStrengthInput");
            _materialBrushStrengthInput = this.FindControl<ValueInput>("MaterialBrushStrengthInput");
            _materialBrushDensityInput = this.FindControl<ValueInput>("MaterialBrushDensityInput");
            _materialCharacterInput = this.FindControl<ValueInput>("MaterialCharacterInput");
            _spiralNormalInfluenceCheckBox = this.FindControl<CheckBox>("SpiralNormalInfluenceCheckBox");
            _basisDebugModeCombo = this.FindControl<ComboBox>("BasisDebugModeCombo");
            _microLodFadeStartInput = this.FindControl<ValueInput>("MicroLodFadeStartInput");
            _microLodFadeEndInput = this.FindControl<ValueInput>("MicroLodFadeEndInput");
            _microRoughnessLodBoostInput = this.FindControl<ValueInput>("MicroRoughnessLodBoostInput");
            _envIntensityInput = this.FindControl<ValueInput>("EnvIntensityInput");
            _envRoughnessMixInput = this.FindControl<ValueInput>("EnvRoughnessMixInput");
            _envIntensityResetButton = this.FindControl<Button>("EnvIntensityResetButton");
            _envRoughnessMixResetButton = this.FindControl<Button>("EnvRoughnessMixResetButton");
            _envTopRInput = this.FindControl<ValueInput>("EnvTopRInput");
            _envTopGInput = this.FindControl<ValueInput>("EnvTopGInput");
            _envTopBInput = this.FindControl<ValueInput>("EnvTopBInput");
            _envBottomRInput = this.FindControl<ValueInput>("EnvBottomRInput");
            _envBottomGInput = this.FindControl<ValueInput>("EnvBottomGInput");
            _envBottomBInput = this.FindControl<ValueInput>("EnvBottomBInput");
            _envPresetCombo = this.FindControl<ComboBox>("EnvPresetCombo");
            _envTonemapCombo = this.FindControl<ComboBox>("EnvTonemapCombo");
            _envExposureInput = this.FindControl<ValueInput>("EnvExposureInput");
            _envBloomStrengthInput = this.FindControl<ValueInput>("EnvBloomStrengthInput");
            _envBloomThresholdInput = this.FindControl<ValueInput>("EnvBloomThresholdInput");
            _envBloomKneeInput = this.FindControl<ValueInput>("EnvBloomKneeInput");
            _envBloomKernelShapeCombo = this.FindControl<ComboBox>("EnvBloomKernelShapeCombo");
            _environmentManualSettingsPanel = this.FindControl<StackPanel>("EnvironmentManualSettingsPanel");
            _envHdriPathTextBox = this.FindControl<TextBox>("EnvHdriPathTextBox");
            _envHdriApplyButton = this.FindControl<Button>("EnvHdriApplyButton");
            _envHdriClearButton = this.FindControl<Button>("EnvHdriClearButton");
            _envHdriBlendInput = this.FindControl<ValueInput>("EnvHdriBlendInput");
            _envHdriRotationInput = this.FindControl<ValueInput>("EnvHdriRotationInput");
            _shadowEnabledCheckBox = this.FindControl<CheckBox>("ShadowEnabledCheckBox");
            _shadowSourceModeCombo = this.FindControl<ComboBox>("ShadowSourceModeCombo");
            _shadowStrengthInput = this.FindControl<ValueInput>("ShadowStrengthInput");
            _shadowSoftnessInput = this.FindControl<ValueInput>("ShadowSoftnessInput");
            _shadowDistanceInput = this.FindControl<ValueInput>("ShadowDistanceInput");
            _shadowScaleInput = this.FindControl<ValueInput>("ShadowScaleInput");
            _shadowQualityInput = this.FindControl<ValueInput>("ShadowQualityInput");
            _shadowStrengthResetButton = this.FindControl<Button>("ShadowStrengthResetButton");
            _shadowSoftnessResetButton = this.FindControl<Button>("ShadowSoftnessResetButton");
            _shadowQualityResetButton = this.FindControl<Button>("ShadowQualityResetButton");
            _shadowGrayInput = this.FindControl<ValueInput>("ShadowGrayInput");
            _shadowDiffuseInfluenceInput = this.FindControl<ValueInput>("ShadowDiffuseInfluenceInput");
            _brushPaintEnabledCheckBox = this.FindControl<CheckBox>("BrushPaintEnabledCheckBox");
            _brushPaintChannelCombo = this.FindControl<ComboBox>("BrushPaintChannelCombo");
            _brushTypeCombo = this.FindControl<ComboBox>("BrushTypeCombo");
            _brushPaintColorPicker = this.FindControl<ColorPicker>("BrushPaintColorPicker");
            _colorChannelPanel = this.FindControl<StackPanel>("ColorChannelPanel");
            _paintChannelTargetValuePanel = this.FindControl<StackPanel>("PaintChannelTargetValuePanel");
            _paintChannelTargetValueLabel = this.FindControl<TextBlock>("PaintChannelTargetValueLabel");
            _paintChannelTargetValueInput = this.FindControl<ValueInput>("PaintChannelTargetValueInput");
            _paintChannelTargetDisplayText = this.FindControl<TextBlock>("PaintChannelTargetDisplayText");
            _paintLayerListBox = this.FindControl<ListBox>("PaintLayerListBox");
            _paintLayerNameTextBox = this.FindControl<TextBox>("PaintLayerNameTextBox");
            _addPaintLayerButton = this.FindControl<Button>("AddPaintLayerButton");
            _renamePaintLayerButton = this.FindControl<Button>("RenamePaintLayerButton");
            _deletePaintLayerButton = this.FindControl<Button>("DeletePaintLayerButton");
            _focusPaintLayerCheckBox = this.FindControl<CheckBox>("FocusPaintLayerCheckBox");
            _clearPaintLayerFocusButton = this.FindControl<Button>("ClearPaintLayerFocusButton");
            _paintLayerVisibleCheckBox = this.FindControl<CheckBox>("PaintLayerVisibleCheckBox");
            _paintLayerBlendModeCombo = this.FindControl<ComboBox>("PaintLayerBlendModeCombo");
            _paintLayerOpacityInput = this.FindControl<ValueInput>("PaintLayerOpacityInput");
            _paintMaskResolutionCombo = this.FindControl<ComboBox>("PaintMaskResolutionCombo");
            _paintMaskResolutionMemoryText = this.FindControl<TextBlock>("PaintMaskResolutionMemoryText");
            _scratchAbrasionTypeCombo = this.FindControl<ComboBox>("ScratchAbrasionTypeCombo");
            _scratchContextBannerBorder = this.FindControl<Border>("ScratchContextBannerBorder");
            _scratchPrimaryPanel = this.FindControl<StackPanel>("ScratchPrimaryPanel");
            _generalPaintPrimaryPanel = this.FindControl<StackPanel>("GeneralPaintPrimaryPanel");
            _brushAdvancedExpander = this.FindControl<Expander>("BrushAdvancedExpander");
            _generalPaintAdvancedPanel = this.FindControl<StackPanel>("GeneralPaintAdvancedPanel");
            _scratchAdvancedPanel = this.FindControl<StackPanel>("ScratchAdvancedPanel");
            _brushSizeInput = this.FindControl<ValueInput>("BrushSizeInput");
            _brushOpacityInput = this.FindControl<ValueInput>("BrushOpacityInput");
            _brushDarknessInput = this.FindControl<ValueInput>("BrushDarknessInput");
            _brushSpreadInput = this.FindControl<ValueInput>("BrushSpreadInput");
            _paintCoatMetallicInput = this.FindControl<ValueInput>("PaintCoatMetallicInput");
            _paintCoatRoughnessInput = this.FindControl<ValueInput>("PaintCoatRoughnessInput");
            _clearCoatAmountInput = this.FindControl<ValueInput>("ClearCoatAmountInput");
            _clearCoatRoughnessInput = this.FindControl<ValueInput>("ClearCoatRoughnessInput");
            _anisotropyAngleInput = this.FindControl<ValueInput>("AnisotropyAngleInput");
            _scratchWidthInput = this.FindControl<ValueInput>("ScratchWidthInput");
            _scratchDepthInput = this.FindControl<ValueInput>("ScratchDepthInput");
            _scratchResistanceInput = this.FindControl<ValueInput>("ScratchResistanceInput");
            _scratchDepthRampInput = this.FindControl<ValueInput>("ScratchDepthRampInput");
            _scratchExposeColorRInput = this.FindControl<ValueInput>("ScratchExposeColorRInput");
            _scratchExposeColorGInput = this.FindControl<ValueInput>("ScratchExposeColorGInput");
            _scratchExposeColorBInput = this.FindControl<ValueInput>("ScratchExposeColorBInput");
            _scratchExposeMetallicInput = this.FindControl<ValueInput>("ScratchExposeMetallicInput");
            _scratchExposeRoughnessInput = this.FindControl<ValueInput>("ScratchExposeRoughnessInput");
            _clearPaintMaskButton = this.FindControl<Button>("ClearPaintMaskButton");
            _newProjectButton = this.FindControl<Button>("NewProjectButton");
            _changeProjectTypeButton = this.FindControl<Button>("ChangeProjectTypeButton");
            _openProjectButton = this.FindControl<Button>("OpenProjectButton");
            _saveProjectButton = this.FindControl<Button>("SaveProjectButton");
            _saveProjectAsButton = this.FindControl<Button>("SaveProjectAsButton");
            _renderButton = this.FindControl<Button>("RenderButton");
            _topProjectStatusText = this.FindControl<TextBlock>("TopProjectStatusText");
            _contextStripNodeText = this.FindControl<TextBlock>("ContextStripNodeText");
            _contextStripToolText = this.FindControl<TextBlock>("ContextStripToolText");
            _contextStripHintText = this.FindControl<TextBlock>("ContextStripHintText");
            _brushDockPopup = this.FindControl<Popup>("BrushDockPopup");
            _viewportHostBorder = this.FindControl<Border>("ViewportHostBorder");
            _viewportBrushDock = this.FindControl<Border>("ViewportBrushDock");
            _brushDockDragHandle = this.FindControl<Border>("BrushDockDragHandle");
            _brushQuickToggleButton = this.FindControl<Button>("BrushQuickToggleButton");
            _brushQuickColorButton = this.FindControl<Button>("BrushQuickColorButton");
            _brushQuickScratchButton = this.FindControl<Button>("BrushQuickScratchButton");
            _brushQuickEraseButton = this.FindControl<Button>("BrushQuickEraseButton");
            _brushQuickRustButton = this.FindControl<Button>("BrushQuickRustButton");
            _brushQuickWearButton = this.FindControl<Button>("BrushQuickWearButton");
            _brushQuickGunkButton = this.FindControl<Button>("BrushQuickGunkButton");
            _brushQuickSprayButton = this.FindControl<Button>("BrushQuickSprayButton");
            _brushQuickStrokeButton = this.FindControl<Button>("BrushQuickStrokeButton");
            _brushQuickNeedleButton = this.FindControl<Button>("BrushQuickNeedleButton");
            _brushQuickScuffButton = this.FindControl<Button>("BrushQuickScuffButton");
            _brushQuickAddLayerButton = this.FindControl<Button>("BrushQuickAddLayerButton");
            _brushQuickClearMaskButton = this.FindControl<Button>("BrushQuickClearMaskButton");
            _materialAlbedoMapPathText = this.FindControl<TextBlock>("MaterialAlbedoMapPathText");
            _materialNormalMapPathText = this.FindControl<TextBlock>("MaterialNormalMapPathText");
            _materialRoughnessMapPathText = this.FindControl<TextBlock>("MaterialRoughnessMapPathText");
            _materialMetallicMapPathText = this.FindControl<TextBlock>("MaterialMetallicMapPathText");
            _materialNormalMapStrengthPanel = this.FindControl<StackPanel>("MaterialNormalMapStrengthPanel");
            _centerLightButton = this.FindControl<Button>("CenterLightButton");
            if (!HasRequiredControls())
            {
                return;
            }

            ApplyProjectTypeInspectorVisibility();
            LoadUserReferenceProfiles();
            InitializeViewportAndSceneBindings();
            WireButtonHandlers();
            WireControlPropertyHandlers();
            InitializeUpdatePolicy();
            InitializePrecisionControls();
            InitializeBrushContextAndHudUx();
            InitializeInspectorUx();
            InitializeMaterialGraphEditor();
            InitializeUndoRedoSupport();
            WireOpenedHandlers();
            InitializeNativeMenuBar();
            UpdateWindowTitleForProject();
        }

    }
}
